### ISSUE TITLE
grad_cohort and grad_cohort_year

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#126]
From Stephen:
Section 6 Categorical Variables

Add grad_cohort to this section. Text below:

This is a 4-digit number representing the first year of the graduation cohort. The length of the cohort will vary by degree_level as follows:

if degree_level=05, cohort is 3 years
e.g., grad_cohort=2010 contains graduations years (2010, 2011, 2012)
otherwise, cohort is 5 years
e.g., grad_cohort=2010 contains graduations years (2010, 2011, 2012, 2013, 2014)
For tabulations across all cohorts, the grad_cohort will be recorded as 0000.

**Comment by jodyhoonstarr** [comment]
Added the grad cohort in https://github.com/labordynamicsinstitute/qwi_schemas/commit/9570361b9cb425066572d326b6c672f4159732eb

@srt1 what do you want to say for the grad_cohort_year?

**Comment by srt1** [comment]
**Text to include in section 6 for identifiers _grad_cohort_ and _grad_cohort_years_.**

_Feel free to pretty it up, add links, etc._


**grad_cohort**

This is a 4-digit number representing the first year of the graduation cohort. The number of years in the cohort are reported in the separate _grad_cohort_years_ variable. If _grad_cohort_ is 2010 and _grad_cohort_years_ is 3, then the cell includes graduates from (2010, 2011, and 2012).

When tabulating across all cohorts, the value **0000** will be used for grad_cohort.

**grad_cohort_years**

This is the number of years in the cohort of reference (see _grad_cohort_). It varies by _degree_level_.

if _degree_level=05_, _grad_cohort_years=3_ (3 year cohorts for bachelor's degrees).
otherwise, _grad_cohort_years=5_ (5 year cohorts for all other degrees).

Tabulations are not done across degree types, so _grad_cohort_years_ will be reported when _cohort=0000_.

**Comment by srt1** [comment]
If possible, please edit description in 6.16 and 6.17 so that references to _grad_cohort_ and _grad_cohort_years_ are links to each other. This also helps in the appearance of the text. If you think. They are right next to each other, so it's not hard to find, so it's more of a stylistic thing.

Also, do we do anything in the schema for examples, to set them apart? Both of these items contain specific examples to help better describe the use of the variable. Should they be in italics? A little box? Note, this does not include the description of the 0000 field.
