### ISSUE TITLE
create shapefiles directory, document

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#20]
Heath owes me QWI and J2J shapefiles and content explaining how these data were created. This will appear in the forthcoming V4.1d-draft schema. What format should the content take? Should the geography get it's own html page (like the csv_naming conventions page)?  I can modify an existing html page or just send you a word document containing my draft geo content, whichever you prefer.

**Comment by larsvilhuber** [comment]
Provide the documentation as a raw ASCII text file. Dynamic content can be added. See the Versioning document/script how. I'll adjust.

**Comment by heathhayward** [comment]
- How about this for description and sourcing of the components of a shapefile?  the parenthetical could appear after each of the zip files or only after the first one:

4.3.1. State
lehd_state.zip (contains dbf, shx, shp, and prj files as per http://www.digitalpreservation.gov/formats/fdd/fdd000280.shtml)

alternate source URLs could be http://gisgeography.com/arcgis-shapefile-files-types-extensions/ or https://en.wikipedia.org/wiki/Shapefile

- The label_stusps.csv file has a trailing quotation mark in the name field.  I'm not seeing that in the source file I sent you.

otherwise I think this looks great.

**Comment by larsvilhuber** [comment]
@heathhayward See da41dcd...68a9106

**Comment by larsvilhuber** [comment]
@heathhayward actually see 3765f29..68a9106

**Comment by larsvilhuber** [comment]
Can we close this?

**Comment by heathhayward** [comment]
yep, this can be closed.
