### ISSUE TITLE
Adjust description of XLS files for J2J

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#23]
The last set was XLS (I think), but the SAS 9.4 export in the next release will be XLSX.

My plan was to produce one XLSX file per process/state (e.g., J2J-US, J2J-AK, J2JR-US, J2JR-AK, J2JOD-AK, ...). Each "table" would be a single tab on the spreadsheet. The proposed name would be j2j_ak_all.xlsx, unless you can think of something better.  Note, the J2JOD files will continue to have only the state to state flows, since the other tables may exceed the row constraint on the spreadsheet.

We can add the unit to the measures tables along with the earnings variables, though the next release will still be on V4.1d.

**Comment by larsvilhuber** [comment]
@srt1 Can you have a look at this one, see if it still makes sense?

**Comment by srt1** [comment]
I don't know exactly what the question is here; there are two spreadsheets per process, one for seasonally adjusted and one not seasonally adjusted. They haven't changed for the last few releases. What are you looking for?

**Comment by larsvilhuber** [comment]
We have never (even in previous releases) adequately documented them in the schema. Can we do that?

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by larsvilhuber** [comment]
@srt1 : bumping this smallish issue up

**Comment by srt1** [comment]
The spreadsheets have not been expanded to include the more detailed tabulations - they still continue to include the same set of tabs.

What exactly to you want to see in the way of documentation of this? There are two files, one adjusted, one not adjusted, for each of J2J, J2JR, J2JOD. The columns are exactly the same as the CSV columns. The tabs are one for each of the original set of tables (the J2JOD only contains data for the highest level table - others are suppressed with a note).

**Comment by srt1** [comment]
_Adding comment added to other ticket_

... and hence my confusion on #23. If we are not detailing exactly which tables are being presented in the schema, I don't see a reason to do so in the Excel files; and since the Excel files are otherwise just the csv files themselves, plus a few lines of headers, I don't see very much there to actually document. The header lines themselves are (for example):
Job-to-Job Flow Counts, Alaska

Source: United States Census Bureau
Release: R2017Q2
Data Schema: V4.2b-draft
Tabulation: by state, all firms, all workers  (Not Seasonally Adjusted)

If you like, feel free to set up a template of what you are looking for there, and I can fill in the missing info.

**Comment by larsvilhuber** [comment]
@srt1 : let me know if this works for you.

**Comment by srt1** [comment]
Sure.
