### ISSUE TITLE
Say something about the state_avail.txt file

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#27]

**Comment by larsvilhuber** [comment]
Should be CSV, should be named differently, should be structured as data.

**Comment by larsvilhuber** [comment]
For J2JOD, it shows the date range that another state could serve as origin or destination for a flow from the reference state.  http://lehd.ces.census.gov/data/j2j/R2016Q1/j2jod/ak/state_avail_j2jod.txt

**Comment by larsvilhuber** [comment]
Suggestion: add the line about US with an appropriate time range to the state_avail.txt. Let the US directory have a state_avail with only a line for the sole destination (US). That makes no exception across files.

Couple of nitpicking comments (since we are in draft), but (we've said this before): is state_avail.txt  metadata or data? 

If metadata:

* I would add the tag "J2JOD" the same as for version_j2jod.txt, so that the first three tags are in the same position. 

If data:

- state_avail should be  j2jod_{state}_avail.csv
- the file has the state abbreviation in caps. We are all over the place with state abbrevs, but the actual data files have only the numeric FIPS. Drop it. 
- header row

Separately, I have an issue with label_stusps.csv (which is the only file with the actual state-abbreviation, and has caps).  I now realize that it should be "stusps,label" not "geography,stusps" to conform to all others label files.

**Comment by srt1** [comment]
I have reworked the code that generates those files. The version.txt and geo_avail files for the MSAs have been collapsed into a single file for each, rather than one for every MSA. I has also converted the geo_avail file to a csv, as had previously been suggested by Lars. The geo_avail files are all named identically, geo_avail_j2jod.csv, i.e., they do not use a state abbreviation in the name. Let me know if you want me to change that (j2jod_metro_geo_avail.csv.gz, j2jod_al_geo_avail.csv.gz,...?).  A one-line version has been created for region=US, since it contains only US-level data (no state/metro).


**(version_j2jod.txt file for all MSAs)**

```
> more version_j2jod.txt 
J2JOD MSA 01999 2001:2-2015:4 V??????? R2016Q4 j2jodpu_us_20170209_1318
J2JOD MSA 02999 2000:4-2015:4 V??????? R2016Q4 j2jodpu_us_20170209_1318
J2JOD MSA 04999 2004:2-2015:4 V??????? R2016Q4 j2jodpu_us_20170209_1318
...
```

**(geo_avail_j2jod.csv file for all MSAs)**

```
> gunzip -c geo_avail_j2jod.csv.gz |more
geo_level,geography,geo_level_linked,geography_linked,start_year,start_quarter,end_year,end_quarter
B,01999,B,01999,2001,2,2015,4
B,01999,B,02999,2001,2,2015,4
B,01999,B,04999,2004,2,2015,4
B,01999,B,05999,2002,4,2015,4
B,01999,B,06999,2001,2,2015,4
...
B,01999,N,00,2001,2,2015,4
B,01999,S,01,2001,2,2015,4
B,01999,S,02,2001,2,2015,4
B,01999,S,04,2004,2,2015,4
...
B,02999,B,01999,2001,2,2015,4
B,02999,B,02999,2000,4,2015,4
B,02999,B,04999,2004,2,2015,4
...

```
 **(geo_avail_j2jod.csv file for Alaska)**

```
> gunzip -c geo_avail_j2jod.csv.gz |more
geo_level,geography,geo_level_linked,geography_linked,start_year,start_quarter,end_year,end_quarter
S,02,N,00,2000,2,2015,4
S,02,S,01,2001,2,2015,4
S,02,S,02,2000,2,2015,4
S,02,S,04,2004,2,2015,4
S,02,S,05,2002,4,2015,4
S,02,S,06,2000,2,2015,4
S,02,S,08,2000,2,2015,4
S,02,S,09,2000,2,2015,4
S,02,S,10,2000,2,2015,4
S,02,S,11,2005,3,2015,4
S,02,S,12,2000,2,2015,4
S,02,S,13,2000,2,2015,4
S,02,S,15,2000,2,2015,4
```
**(geo_avail_j2jod.csv file for US)**

```
> gunzip -c geo_avail_j2jod.csv.gz 
geo_level,geography,geo_level_linked,geography_linked,start_year,start_quarter,end_year,end_quarter
N,00,N,00,2000,2,2015,4

```

**Comment by srt1** [comment]
Just reviewing Lars' previous comment, and he already suggested renaming the files:
j2jod_[state]_avail.csv

I'll do that; what is the state for the MSA regions? are we calling it msa/metro/cbsa/other? I'm assuming it is the same thing that the directory will be named.

**Comment by larsvilhuber** [comment]
Call it metro. MSA is ambiguous, CBSA is too expansive.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://www.vilhuber.com/lars/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by srt1** [comment]
I think Heath had made the same vote. So nameth the directories.

```
//lehd.ces.census.gov/data/j2j/R2016Q4/j2j/us
//lehd.ces.census.gov/data/j2j/R2016Q4/j2j/ak
//lehd.ces.census.gov/data/j2j/R2016Q4/j2j/metro

//lehd.ces.census.gov/data/j2j/R2016Q4/j2jr/us
//lehd.ces.census.gov/data/j2j/R2016Q4/j2jr/ak
//lehd.ces.census.gov/data/j2j/R2016Q4/j2jr/metro

//lehd.ces.census.gov/data/j2j/R2016Q4/j2jod/us
//lehd.ces.census.gov/data/j2j/R2016Q4/j2jod/ak
//lehd.ces.census.gov/data/j2j/R2016Q4/j2jod/metro

```

**Comment by srt1** [comment]
Proposed modification:

The original version of this table contained only one region on each line, with the implication that the region could be either the origin or destination. For 4.2a-draft, I modified it to explicitly include the reference and "linked" state. The intent was that the linked state could be either the origin or the destination. Within a state release, the availability is symmetric.

`geo_level,geography,geo_level_linked,geography_linked,...`

It would perhaps make more sense to exactly follow the schema:

`geo_level,geography,geo_level_orig,geography_orig`

We would, however, have to double the number of records on the table, except for the one where the origin and destination is the same, of course. This seems perfectly sensible to me, but I just wanted to check that others agreed.

**Comment by srt1** [comment]
_From: Lars Vilhuber <lars.vilhuber@cornell.edu>
Sent: Friday, March 10, 2017 9:57 AM_

My preference would be to stick to the sparser original implementation. Providing the information that it's symmetric is important, and should be added. The fact that the variables are not the same is fine. Programmers can flip around what they use as the FK, just as long as it's documented.

--

**Comment by srt1** [comment]
_(follow up message from SRT in long thread from 3/10)_

Well, as far as the j2jod_avail file goes, in working through the permutations, I think I've concluded that you really do need to report the "duplicate" records. The reason I see is this: in the metro directory, we have a single table containing all A-B metro area pairs. The A-B pair would have the same available range as the B-A pair; however, if we filter the file to contain all the distinct pairs, you get a weird result: if you are looking for a specific metro area A, it could be either in the first or second position. I think it would make it easier for users to duplicate the information, so that it follows the geography/geography_orig convention. There is less of an obvious need to do the same on the individual state directories, since the reference state will always be the origin or destination, but for consistency, I think we should follow the same rule.

**Comment by srt1** [comment]
**Proposed text and table for data schema** 



From: Stephen R Tibbets (CENSUS/CES FED)
Sent: Monday, April 3, 2017 6:01 PM
To: lars.vilhuber@cornell.edu
Subject: Re: J2J public use files - production integration
 

Lars,


I added a note about data suppression. This is actually not relevant for the 4.1a release, since the overall ranges are restricted so that we do not have to apply suppression. The plan is to expand the files in the future so that every state (region) release contains all the cells where the state is either an origin or destination, not just that for those quarters where the state totals are releasable. When we do that, we will have to apply some suppressions. Also, the metro comment is for a future release.


Let me know what you think.


Thanks,

Stephen




J2JOD_ST_AVAIL.CSV.GZ


Regions will appear in the J2J data in varying time ranges because of differential availability, which is noted in the version*.txt files. Because the origin-destination (J2JOD) data link two regions, we provide an auxiliary file with the time range that cells containing data for each geographic pairing may appear in a data release. The reference region will always be either the origin or the destination. National tabulations contain records where both origin and destination are geo_level=N; state tabulations contain records where geo_level in (N,S); metro tabulations contain records where geo_level in (N,S,B). Data may be suppressed for certain combinations of regions and quarters because the estimates do not meet Census Bureau publication standards.



```
Variable,Type,Label

geo_level,Char(1),Geographic level of destination region

geography,Char(8),Geography code of destination region

geo_level_orig,Char(1),Geographic level of origin region

geography_orig,Char(8),Geography code of origin region

start_year,Num,First year regional pair may be observed

start_quarter,Num,First quarter regional pair may be observed

end_year,Num,Last year regional pair may be observed

end_quarter,Num,Last quarter regional pair may be observed
```

**Comment by larsvilhuber** [comment]
@srt1 have a look at what I've done for the version files, in addition to the avail files.
