### ISSUE TITLE
All, all_aggregations shall remain in draft form

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#28]

**Comment by larsvilhuber** [comment]
@srt1 : do you remember what this was about?

**Comment by srt1** [comment]
Vaguely; I had originally requested that the label_agg_level be left in draft mode last summer, since there were some open questions, particularly related to the troublesome "ownership" category. You initially agreed, but then last October I think became convinced by Heath of the need to release the table in the non-draft schema 4.1.0, for use in the J2J app. Hence, it was moved off the draft schemas back then, and this ticket was basically voided. We still have a potential issue on how to deal with the ownership code, which we would need to consider if we ever get around to adding agg_level onto QWI, or if we ever wanted to interact by ownership in J2JOD tables (not on the current agenda, is sort of implicitly done with firm age/size tabulations).
