### ISSUE TITLE
Updated 2015-geo SHP files

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/qwi_schemas#44]
The SHP files are updated to reflect boundaries for 2015 geography

**Comment by heathhayward** [comment]
[schema_shp.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/822056/schema_shp.zip)

**Comment by larsvilhuber** [comment]
The structure of the lehd_shp_gX.zip files has internally changed. Is that intentional? Does that matter for SHP files? 

Old files (ex. lehd_shp_gb.zip:)

- lehd_cbsa.dbf
- lehd_cbsa.prj
- lehd_cbsa.shp
- lehd_dbsa.shx

New files are

- lehd_shp_gb.dbf
- lehd_shp_gb.prj

etc. plus additional files (*.CPG, *.sbx, *.sbn) that were not previously there.

@heathhayward : please clarify.

**Comment by heathhayward** [comment]
I didn't realize the files inside the lehd_shp_g$.zip files had different names than their zipped name in V4.1.0.  I believe file names should all be identical (especially since the "gb" file has "cbsa" in it's internal file names).  I'll remove extraneous files and zip each shapefile individually, but I'd like to keep the names as I have them if you approve.  As shown below:

[lehd_shp_gs.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/824518/lehd_shp_gs.zip)
[lehd_shp_gw.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/824520/lehd_shp_gw.zip)
[lehd_shp_gb.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/824519/lehd_shp_gb.zip)
[lehd_shp_gc.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/824521/lehd_shp_gc.zip)
[lehd_shp_gm.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/824522/lehd_shp_gm.zip)

**Comment by larsvilhuber** [comment]
Yes, that's fine.

I don't use the SHP files - how "wrong" was the 4.1.0 version? Can we just replace those files ("correct") them, or does that break things? (breaking things is not allowed after releasing 4.1.0, editing inconsequential things is...)

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://www.vilhuber.com/lars/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by heathhayward** [comment]
We can rename them in the 4.1.0 version, that won't break anything.  I'll rename them and drop them here.  Give me a minute.

**Comment by heathhayward** [comment]
[lehd_shp_gm.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/824568/lehd_shp_gm.zip)
[lehd_shp_gs.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/824565/lehd_shp_gs.zip)
[lehd_shp_gw.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/824564/lehd_shp_gw.zip)
[lehd_shp_gb.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/824566/lehd_shp_gb.zip)
[lehd_shp_gc.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/824567/lehd_shp_gc.zip)

**Comment by larsvilhuber** [comment]
Later files (for #49) commited with 3d66200f7b1020def25a572bf6133198a00144b5
