### ISSUE TITLE
Review "concept" field for MJobStart/MJobEnd

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#60]
The MJobStart/MJobEnd variables are recorded as "Employment" variables in V4.2a-draft. These are really more flow measures, rather than stock measures, and might be more appropriately labelled Hires/Separations, if we allow those labels to be a generalized a bit. We should consider modifying these.

https://lehd.ces.census.gov/data/schema/V4.2a-draft/lehd_public_use_schema.html#_job_to_job_flow_counts_j2j

**Comment by srt1** [comment]
Describing the issue:

From an economic perspective, we divide measures into _stock_ and _flow_. Stock measures provide the total count at a point in time (e.g., end of quarter jobs, stayers), and flow measures describe the changes to those stocks (hires, separations, etc.). The **Main Job Start/End** measures are changes to the stock measures at a point in time, so we think of them as flow measures.  Though they do not necessarily involve a hire or separation, most of them do (over 90%).  These measures really do not fit in with the other employment measures, which are more clearly stock measures. They are a subset of employment measures, but you could argue that so are all the hires and separation measures, so that is not a very useful way to look at it.

**Heath**: can you describe precisely why in the application these measures need to be handled differently? That could help us think of an alternate way to describe the concept.

Thanks.,

**Comment by heathhayward** [comment]
From my perspective, I only care about this field in terms of how it differentiates measures that we want to handle differently in the application.  The "Concept" field allows the application's sentence construction mechanism to be data driven in terms of describing the directionality of flows into states and industries. Since MJobStart/End do not involved moving into or out of a state or industry (only change of dominance), it has more in common with MainB/E from the perspective of creating a simple sentence for users to understand.  

Perhaps we should remove the concept field from the non-j2japp files in order to eliminate this point of contention.  The field was only created for the application and it's working as intended.   If Stephen wants to create an additional term to describe the "change of dominance" concept for these two measures, that would be fine for me.

**Comment by larsvilhuber** [comment]
I strongly encourage maintaining the concept field, but getting its contents right. Concept is part of most metadata schemata I've seen. The issue here is one of application of a taxonomy (valid values for the concept field) rather than existence of the concept field.

I would suggest providing the algorithm for sentence creation that is being used. I do detect a slight discrepancy between what Stephen describes and what Heath describes, so it might be relevant to see the actual application of these sentences.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by srt1** [comment]
The Start/End variables are potentially a change in the geography/industry of an individual's dominant employment, which is what we care about for the purposes of J2J, even if the person wasn't actually hired or separated to/from that "main" job. We explicitly remove secondary jobs from the universe - we tried to think about ways of developing measures with the secondary jobs, but it was much more complicated and confused. I would disagree that it has more in common structurally with MainB/MainE, but perhaps in certain dynamic phrases it could.  Some sentences might have to be worded a little differently, so an example would be very helpful.

**Comment by srt1** [comment]
OK, so it is a battle of prepositions. I would agree that the prepositions do not work equally well for all measures, the the start/end ones being particularly awkward:

_Separations_ **from** Manufacturing in North Dakota
_Hires_ **to** Manufacturing in North Dakota
_Employment (Beginning of Quarter)_ **for** Manufacturing in North Dakota
_Main Job Starts_ **for** Manufacturing in North Dakota 
_Main Job Ends_ **for** Manufacturing in North Dakota 

I really don't have an alternative preposition; to/from is awkward for main job starts/ends, "for" is OK, one could even use "in" twice in the sentence. But I stick to my basic contention: the main job start/end are measures of transition (flow) - employment is a measure of a stock.

**Comment by larsvilhuber** [comment]
Two options:

a) The trigger for the prepositions is the Indicator Variable, not the Concept.
b) The taxonomy for concept is augmented to have

Concept,Explanation
Hire,"A flow into a new job"
Separations,"A flow out of an existing job"
Employment,"State of being in the employ of an establishment"
Dominance Change,"A change in the character of employment, which may involve a separation or a hire"

(p.s., this taxonomy should be part of the schema...)

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by srt1** [comment]
I am with Lars, I really do like the addition of the "Concept" field. And not that the mechanical construction of the variables needs to drive how we present it, I think I could provide a little insight here:

There are two tables I use when I develop the J2J tabulations: an employment history table for each individual, which is used to count total employment in each quarter, and a transition table that contains a record every time the main job changes. This contains the last quarter job A is your main job, and the first quarter job B is your main job, along with other information describing the transition. (Technically, this table is itself a product of the earnings history, of course). When calculating the measures, I need to do three passes:

1. Tabulate the separations measures by the last quarter of MainB (including MJobEnd)
2. Tabulate the accessions measures by the first quarter of MainE (including MJobStart)
3. Tabulate total employment in each quarter (MainB, MainE, Job Stayers, etc.)

These are actually broken up into several hundred jobs to do 2000 hours of processing in a couple of days, but you get the picture. I then merge all of the variables together by quarter and the categorical variables, so by the time you see it everything comes back together. But that doesn't fundamentally change the organizational structure of the variables. Hence, I really liked the "concept", but it wasn't quite right.

One further note: the "Earnings" concept loses the distinction between earnings associated with accession/separations/stock employment measures. It's not absolutely necessary to maintain that in the schema table. At some point you get too many concepts, and it uses its utility. On the plus side, since each earnings measure is associated with a base, you can derive it directly from that, which is probably better.

**Comment by srt1** [comment]
... so, pending further protest, I will switch the "concept" fields on the j2j_measures.csv file to Hires/Separations. We could add an explanatory note to the schema expanding on what those terms mean, in the concept context:

* **Hire**: Measure derived from the the first quarter that a job is the main source of income (usually a hire)
* **Separation**: Measure derived from the last quarter that a job is the main source of income (usually a separation)
* **Employment**: Measure counting the stock of all jobs at a point in time
* **Earnings**: Measure of average earnings associated with a base employment or job transition measure

Ideally, there would be a more generic term than hires or separations, but I can't think of any. I think this approach works.

**Comment by srt1** [comment]
P.S. - and Heath figures out an alternative mechanism to drive the prepositions. (Sorry about taking over that variable, but you did come up with a good enhancement, and I'm just trying to apply it appropriately.)

**Comment by srt1** [comment]
Sorry; just reading Lars' comment again. I'd prefer to keep the directionality on the MJobStart/MJobEnd measures - I think dropping them into a _Dominance Change_ category is a bit more artificial than associated them with hires/separations. Plus, as my comment on the mechanics earlier suggests, they belong together.

**Comment by heathhayward** [comment]
The problem here is we are trying to align two sets of requirements into one field: 1) what the application needs and 2) the mechanics of how these measures are constructed.  If you took a step back and had free reign to create a new data field that would help users understand some key concepts in the data, what would you create?  Maybe a field where "Stock" and "Flow" are the key values?  And maybe even an additional field that expands the "Flow" value into "Hire" and "Separation"?  There's no reason for you to be constrained by the values I created for an entirely different purpose.

As it stands, Stephen's passion for MJobStart/End being Hires/Separations has convinced me that it's ok for J2J Explorer to have sentences such as:

Main Job Starts to Manufacturing in North Dakota
Main Job Ends from Manufacturing in North Dakota

So we can share the Concept field for the time being.  I reserve the right to create my own data field in the "j2japp" file as application requirements demand.  And you owe me a beer for stealing my variable!

**Comment by srt1** [comment]
One more modified copy, this time with my preferred Hire/Separation assignment for MJobStart/MJobEnd. Still up for discussion if I haven't bored you into submission.

[vars-schema-4.2b-draft.tar.gz](https://github.com/labordynamicsinstitute/qwi_schemas/files/1212940/vars-schema-4.2b-draft.tar.gz)

**Comment by larsvilhuber** [comment]
See also #54 , commit 67655ded29ffa366ee97b53721a7d8a6bf58f2de on Aug 15.

**Comment by srt1** [comment]
Did we add a description of the "Concept" field in the schema?  The commit referenced appears to be only adding the I'm repeating (and slightly editing) my proposal in earlier comment here:

* **Hire**: Transition measure associated with the the first quarter that a job is the main source of income (usually a hire)
* **Separation**: Transition measure associated with the last quarter that a job is the main source of income (usually a separation)
* **Employment**: Measure counting the stock of all jobs at a point in time
* **Earnings**: Measure of average earnings associated with a base employment or job transition measure

Related note: the Concept for the J2JOD counts was previously **Flow**, but that has reverted to **Hire** with this (See comments in #41).

**Comment by larsvilhuber** [comment]
@srt1 : I've added an explanation of what the Concept field contains, but not explained the terms (that's not in the doc, that's a taxonomy that we will need to flesh out. There are issues with your taxonomy, so for now, let's just roll with it as is... (or remove it from the V4.1.x series again)

**Comment by larsvilhuber** [comment]
P.S. the above change is in the V4.1.3a-draft branch.

**Comment by srt1** [comment]
I don't deny there are issues with how I've laid out the concepts, but I think it's an improvement from what it was before. I think they were really problematic in the earlier release of 4.2a-draft. Implement as you see fit.

**Comment by larsvilhuber** [comment]
Err. correction - above changes are in V4.2b-draft.

**Comment by larsvilhuber** [comment]
My key point about it is: it's not perfect because it is actually wrong. Your "Hire" concept works when there's a main job, but does not work when it's a simple job accession (such as in the variable "Hires (All Accessions)"... ). So I'm fine with issues, but not fine with things that I know from the start are wrong. 

That being said, it's very good to nail this down, and it may lead to revisions of the concepts as they are applied, for the better. May not make it into V4.2b-draft, but should certainly make it into V4.2.0 final...

**Comment by larsvilhuber** [comment]
See 1b6fb67..c8d3309 for a draft inclusion of a concept taxonomy.

**Comment by larsvilhuber** [comment]
@srt1 : have a look at the last commit here.

**Comment by srt1** [comment]
As far as I can tell, these modifications look fine for the draft version. Final taxonomy of concepts open for future review.
