### ISSUE TITLE
Add "us" directory and us version of label_geography.csv to schema pages

### ISSUE THREAD

**Issue by heathhayward** [labordynamicsinstitute/qwi_schemas#9]
only for schema versions 4.0.4, 4.0.5 and all subsequent versions.

**Comment by larsvilhuber** [comment]
We have coordinated on this, and V4.0.4 will not get a us/ directory. This is not needed for the US files that reference label_geography_us.csv, since the US files actually use a V4.1c-draft version string. The issue was triggered by an error in the R2015Q4 QWI(US) version.txt files, that has been corrected.

**Comment by larsvilhuber** [comment]
Done.
